on:
  push:
    branches:
      - main

name: Build and Push

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/translate-bot:latest .

      - name: Push image to ghcr
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/translate-bot:latest
