on:
  push:
    tags:
      - '*'

name: Build and Push with tag

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract tag version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/$GITHUB_ACTOR/translate-bot
          tags: |
            type=semver,pattern={{version}}
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/$GITHUB_ACTOR/translate-bot:latest
